# Site settings
title: Sunit Jain
email: sunitj@umich.edu
description: > # this means to ignore newlines until "baseurl:"
I am a Bioinformatics professional, currently working as a Research Computing Specialist -- Bioinformatics at the Michigan Geomicrobiology Lab, Department of Earth and Environmental Sciences, University of Michigan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sunitjain.com" # the base hostname & protocol for your site
twitter_username: SunitJain
github_username:  sunitj

# Build settings
markdown: kramdown
